// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/model.user.proto

package net.foreworld.gws.protobuf.model;

public final class User {
  private User() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserProtobufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gws.model.UserProtobuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional string user_name = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string user_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>optional string user_pass = 3;</code>
     */
    java.lang.String getUserPass();
    /**
     * <code>optional string user_pass = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserPassBytes();

    /**
     * <code>optional .gws.model.UserProtobuf.Sex sex = 4;</code>
     */
    int getSexValue();
    /**
     * <code>optional .gws.model.UserProtobuf.Sex sex = 4;</code>
     */
    net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex getSex();
  }
  /**
   * Protobuf type {@code gws.model.UserProtobuf}
   */
  public  static final class UserProtobuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gws.model.UserProtobuf)
      UserProtobufOrBuilder {
    // Use UserProtobuf.newBuilder() to construct.
    private UserProtobuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UserProtobuf() {
      id_ = "";
      userName_ = "";
      userPass_ = "";
      sex_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private UserProtobuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userPass_ = s;
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              sex_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.foreworld.gws.protobuf.model.User.internal_static_gws_model_UserProtobuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.foreworld.gws.protobuf.model.User.internal_static_gws_model_UserProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.foreworld.gws.protobuf.model.User.UserProtobuf.class, net.foreworld.gws.protobuf.model.User.UserProtobuf.Builder.class);
    }

    /**
     * Protobuf enum {@code gws.model.UserProtobuf.Sex}
     */
    public enum Sex
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>FEMALE = 0;</code>
       */
      FEMALE(0),
      /**
       * <code>MALE = 1;</code>
       */
      MALE(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>FEMALE = 0;</code>
       */
      public static final int FEMALE_VALUE = 0;
      /**
       * <code>MALE = 1;</code>
       */
      public static final int MALE_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static Sex valueOf(int value) {
        return forNumber(value);
      }

      public static Sex forNumber(int value) {
        switch (value) {
          case 0: return FEMALE;
          case 1: return MALE;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<Sex>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          Sex> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Sex>() {
              public Sex findValueByNumber(int number) {
                return Sex.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return net.foreworld.gws.protobuf.model.User.UserProtobuf.getDescriptor().getEnumTypes().get(0);
      }

      private static final Sex[] VALUES = values();

      public static Sex valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private Sex(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:gws.model.UserProtobuf.Sex)
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <code>optional string user_name = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string user_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_PASS_FIELD_NUMBER = 3;
    private volatile java.lang.Object userPass_;
    /**
     * <code>optional string user_pass = 3;</code>
     */
    public java.lang.String getUserPass() {
      java.lang.Object ref = userPass_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPass_ = s;
        return s;
      }
    }
    /**
     * <code>optional string user_pass = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserPassBytes() {
      java.lang.Object ref = userPass_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPass_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEX_FIELD_NUMBER = 4;
    private int sex_;
    /**
     * <code>optional .gws.model.UserProtobuf.Sex sex = 4;</code>
     */
    public int getSexValue() {
      return sex_;
    }
    /**
     * <code>optional .gws.model.UserProtobuf.Sex sex = 4;</code>
     */
    public net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex getSex() {
      net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex result = net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex.valueOf(sex_);
      return result == null ? net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (!getUserPassBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userPass_);
      }
      if (sex_ != net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex.FEMALE.getNumber()) {
        output.writeEnum(4, sex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (!getUserPassBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userPass_);
      }
      if (sex_ != net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex.FEMALE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, sex_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.foreworld.gws.protobuf.model.User.UserProtobuf)) {
        return super.equals(obj);
      }
      net.foreworld.gws.protobuf.model.User.UserProtobuf other = (net.foreworld.gws.protobuf.model.User.UserProtobuf) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getUserPass()
          .equals(other.getUserPass());
      result = result && sex_ == other.sex_;
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + USER_PASS_FIELD_NUMBER;
      hash = (53 * hash) + getUserPass().hashCode();
      hash = (37 * hash) + SEX_FIELD_NUMBER;
      hash = (53 * hash) + sex_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.foreworld.gws.protobuf.model.User.UserProtobuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.model.User.UserProtobuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.model.User.UserProtobuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.model.User.UserProtobuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.model.User.UserProtobuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.model.User.UserProtobuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.model.User.UserProtobuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.model.User.UserProtobuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.model.User.UserProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.model.User.UserProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.foreworld.gws.protobuf.model.User.UserProtobuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gws.model.UserProtobuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gws.model.UserProtobuf)
        net.foreworld.gws.protobuf.model.User.UserProtobufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.foreworld.gws.protobuf.model.User.internal_static_gws_model_UserProtobuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.foreworld.gws.protobuf.model.User.internal_static_gws_model_UserProtobuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.foreworld.gws.protobuf.model.User.UserProtobuf.class, net.foreworld.gws.protobuf.model.User.UserProtobuf.Builder.class);
      }

      // Construct using net.foreworld.gws.protobuf.model.User.UserProtobuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        userName_ = "";

        userPass_ = "";

        sex_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.foreworld.gws.protobuf.model.User.internal_static_gws_model_UserProtobuf_descriptor;
      }

      public net.foreworld.gws.protobuf.model.User.UserProtobuf getDefaultInstanceForType() {
        return net.foreworld.gws.protobuf.model.User.UserProtobuf.getDefaultInstance();
      }

      public net.foreworld.gws.protobuf.model.User.UserProtobuf build() {
        net.foreworld.gws.protobuf.model.User.UserProtobuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.foreworld.gws.protobuf.model.User.UserProtobuf buildPartial() {
        net.foreworld.gws.protobuf.model.User.UserProtobuf result = new net.foreworld.gws.protobuf.model.User.UserProtobuf(this);
        result.id_ = id_;
        result.userName_ = userName_;
        result.userPass_ = userPass_;
        result.sex_ = sex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.foreworld.gws.protobuf.model.User.UserProtobuf) {
          return mergeFrom((net.foreworld.gws.protobuf.model.User.UserProtobuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.foreworld.gws.protobuf.model.User.UserProtobuf other) {
        if (other == net.foreworld.gws.protobuf.model.User.UserProtobuf.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getUserPass().isEmpty()) {
          userPass_ = other.userPass_;
          onChanged();
        }
        if (other.sex_ != 0) {
          setSexValue(other.getSexValue());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.foreworld.gws.protobuf.model.User.UserProtobuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.foreworld.gws.protobuf.model.User.UserProtobuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>optional string user_name = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_name = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_name = 2;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_name = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPass_ = "";
      /**
       * <code>optional string user_pass = 3;</code>
       */
      public java.lang.String getUserPass() {
        java.lang.Object ref = userPass_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPass_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_pass = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserPassBytes() {
        java.lang.Object ref = userPass_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPass_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_pass = 3;</code>
       */
      public Builder setUserPass(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userPass_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_pass = 3;</code>
       */
      public Builder clearUserPass() {
        
        userPass_ = getDefaultInstance().getUserPass();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_pass = 3;</code>
       */
      public Builder setUserPassBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userPass_ = value;
        onChanged();
        return this;
      }

      private int sex_ = 0;
      /**
       * <code>optional .gws.model.UserProtobuf.Sex sex = 4;</code>
       */
      public int getSexValue() {
        return sex_;
      }
      /**
       * <code>optional .gws.model.UserProtobuf.Sex sex = 4;</code>
       */
      public Builder setSexValue(int value) {
        sex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .gws.model.UserProtobuf.Sex sex = 4;</code>
       */
      public net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex getSex() {
        net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex result = net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex.valueOf(sex_);
        return result == null ? net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex.UNRECOGNIZED : result;
      }
      /**
       * <code>optional .gws.model.UserProtobuf.Sex sex = 4;</code>
       */
      public Builder setSex(net.foreworld.gws.protobuf.model.User.UserProtobuf.Sex value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        sex_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>optional .gws.model.UserProtobuf.Sex sex = 4;</code>
       */
      public Builder clearSex() {
        
        sex_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gws.model.UserProtobuf)
    }

    // @@protoc_insertion_point(class_scope:gws.model.UserProtobuf)
    private static final net.foreworld.gws.protobuf.model.User.UserProtobuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.foreworld.gws.protobuf.model.User.UserProtobuf();
    }

    public static net.foreworld.gws.protobuf.model.User.UserProtobuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UserProtobuf>
        PARSER = new com.google.protobuf.AbstractParser<UserProtobuf>() {
      public UserProtobuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UserProtobuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UserProtobuf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UserProtobuf> getParserForType() {
      return PARSER;
    }

    public net.foreworld.gws.protobuf.model.User.UserProtobuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gws_model_UserProtobuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gws_model_UserProtobuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031protobuf/model.user.proto\022\tgws.model\"\207" +
      "\001\n\014UserProtobuf\022\n\n\002id\030\001 \001(\t\022\021\n\tuser_name" +
      "\030\002 \001(\t\022\021\n\tuser_pass\030\003 \001(\t\022(\n\003sex\030\004 \001(\0162\033" +
      ".gws.model.UserProtobuf.Sex\"\033\n\003Sex\022\n\n\006FE" +
      "MALE\020\000\022\010\n\004MALE\020\001B(\n net.foreworld.gws.pr" +
      "otobuf.modelB\004Userb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gws_model_UserProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gws_model_UserProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gws_model_UserProtobuf_descriptor,
        new java.lang.String[] { "Id", "UserName", "UserPass", "Sex", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
