// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/method.chat.send.proto

package net.foreworld.gws.protobuf.method.chat;

public final class Send {
  private Send() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestProtobufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gws.method.chat.send.RequestProtobuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string receiver = 1;</code>
     */
    java.lang.String getReceiver();
    /**
     * <code>optional string receiver = 1;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>optional bytes comment = 2;</code>
     */
    com.google.protobuf.ByteString getComment();
  }
  /**
   * Protobuf type {@code gws.method.chat.send.RequestProtobuf}
   */
  public  static final class RequestProtobuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gws.method.chat.send.RequestProtobuf)
      RequestProtobufOrBuilder {
    // Use RequestProtobuf.newBuilder() to construct.
    private RequestProtobuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestProtobuf() {
      receiver_ = "";
      comment_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestProtobuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 18: {

              comment_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.foreworld.gws.protobuf.method.chat.Send.internal_static_gws_method_chat_send_RequestProtobuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.foreworld.gws.protobuf.method.chat.Send.internal_static_gws_method_chat_send_RequestProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf.class, net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf.Builder.class);
    }

    public static final int RECEIVER_FIELD_NUMBER = 1;
    private volatile java.lang.Object receiver_;
    /**
     * <code>optional string receiver = 1;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <code>optional string receiver = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int COMMENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString comment_;
    /**
     * <code>optional bytes comment = 2;</code>
     */
    public com.google.protobuf.ByteString getComment() {
      return comment_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, receiver_);
      }
      if (!comment_.isEmpty()) {
        output.writeBytes(2, comment_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, receiver_);
      }
      if (!comment_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, comment_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf)) {
        return super.equals(obj);
      }
      net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf other = (net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf) obj;

      boolean result = true;
      result = result && getReceiver()
          .equals(other.getReceiver());
      result = result && getComment()
          .equals(other.getComment());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      hash = (37 * hash) + COMMENT_FIELD_NUMBER;
      hash = (53 * hash) + getComment().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gws.method.chat.send.RequestProtobuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gws.method.chat.send.RequestProtobuf)
        net.foreworld.gws.protobuf.method.chat.Send.RequestProtobufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.foreworld.gws.protobuf.method.chat.Send.internal_static_gws_method_chat_send_RequestProtobuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.foreworld.gws.protobuf.method.chat.Send.internal_static_gws_method_chat_send_RequestProtobuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf.class, net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf.Builder.class);
      }

      // Construct using net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        receiver_ = "";

        comment_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.foreworld.gws.protobuf.method.chat.Send.internal_static_gws_method_chat_send_RequestProtobuf_descriptor;
      }

      public net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf getDefaultInstanceForType() {
        return net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf.getDefaultInstance();
      }

      public net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf build() {
        net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf buildPartial() {
        net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf result = new net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf(this);
        result.receiver_ = receiver_;
        result.comment_ = comment_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf) {
          return mergeFrom((net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf other) {
        if (other == net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf.getDefaultInstance()) return this;
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (other.getComment() != com.google.protobuf.ByteString.EMPTY) {
          setComment(other.getComment());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <code>optional string receiver = 1;</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public Builder clearReceiver() {
        
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiver_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString comment_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes comment = 2;</code>
       */
      public com.google.protobuf.ByteString getComment() {
        return comment_;
      }
      /**
       * <code>optional bytes comment = 2;</code>
       */
      public Builder setComment(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        comment_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes comment = 2;</code>
       */
      public Builder clearComment() {
        
        comment_ = getDefaultInstance().getComment();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gws.method.chat.send.RequestProtobuf)
    }

    // @@protoc_insertion_point(class_scope:gws.method.chat.send.RequestProtobuf)
    private static final net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf();
    }

    public static net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestProtobuf>
        PARSER = new com.google.protobuf.AbstractParser<RequestProtobuf>() {
      public RequestProtobuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestProtobuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestProtobuf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestProtobuf> getParserForType() {
      return PARSER;
    }

    public net.foreworld.gws.protobuf.method.chat.Send.RequestProtobuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseProtobufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gws.method.chat.send.ResponseProtobuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .gws.ChatProtobuf chat = 1;</code>
     */
    boolean hasChat();
    /**
     * <code>optional .gws.ChatProtobuf chat = 1;</code>
     */
    net.foreworld.gws.protobuf.Chat.ChatProtobuf getChat();
    /**
     * <code>optional .gws.ChatProtobuf chat = 1;</code>
     */
    net.foreworld.gws.protobuf.Chat.ChatProtobufOrBuilder getChatOrBuilder();
  }
  /**
   * Protobuf type {@code gws.method.chat.send.ResponseProtobuf}
   */
  public  static final class ResponseProtobuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gws.method.chat.send.ResponseProtobuf)
      ResponseProtobufOrBuilder {
    // Use ResponseProtobuf.newBuilder() to construct.
    private ResponseProtobuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseProtobuf() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseProtobuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.foreworld.gws.protobuf.Chat.ChatProtobuf.Builder subBuilder = null;
              if (chat_ != null) {
                subBuilder = chat_.toBuilder();
              }
              chat_ = input.readMessage(net.foreworld.gws.protobuf.Chat.ChatProtobuf.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(chat_);
                chat_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.foreworld.gws.protobuf.method.chat.Send.internal_static_gws_method_chat_send_ResponseProtobuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.foreworld.gws.protobuf.method.chat.Send.internal_static_gws_method_chat_send_ResponseProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf.class, net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf.Builder.class);
    }

    public static final int CHAT_FIELD_NUMBER = 1;
    private net.foreworld.gws.protobuf.Chat.ChatProtobuf chat_;
    /**
     * <code>optional .gws.ChatProtobuf chat = 1;</code>
     */
    public boolean hasChat() {
      return chat_ != null;
    }
    /**
     * <code>optional .gws.ChatProtobuf chat = 1;</code>
     */
    public net.foreworld.gws.protobuf.Chat.ChatProtobuf getChat() {
      return chat_ == null ? net.foreworld.gws.protobuf.Chat.ChatProtobuf.getDefaultInstance() : chat_;
    }
    /**
     * <code>optional .gws.ChatProtobuf chat = 1;</code>
     */
    public net.foreworld.gws.protobuf.Chat.ChatProtobufOrBuilder getChatOrBuilder() {
      return getChat();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (chat_ != null) {
        output.writeMessage(1, getChat());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (chat_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getChat());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf)) {
        return super.equals(obj);
      }
      net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf other = (net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf) obj;

      boolean result = true;
      result = result && (hasChat() == other.hasChat());
      if (hasChat()) {
        result = result && getChat()
            .equals(other.getChat());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasChat()) {
        hash = (37 * hash) + CHAT_FIELD_NUMBER;
        hash = (53 * hash) + getChat().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gws.method.chat.send.ResponseProtobuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gws.method.chat.send.ResponseProtobuf)
        net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.foreworld.gws.protobuf.method.chat.Send.internal_static_gws_method_chat_send_ResponseProtobuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.foreworld.gws.protobuf.method.chat.Send.internal_static_gws_method_chat_send_ResponseProtobuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf.class, net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf.Builder.class);
      }

      // Construct using net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (chatBuilder_ == null) {
          chat_ = null;
        } else {
          chat_ = null;
          chatBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.foreworld.gws.protobuf.method.chat.Send.internal_static_gws_method_chat_send_ResponseProtobuf_descriptor;
      }

      public net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf getDefaultInstanceForType() {
        return net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf.getDefaultInstance();
      }

      public net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf build() {
        net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf buildPartial() {
        net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf result = new net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf(this);
        if (chatBuilder_ == null) {
          result.chat_ = chat_;
        } else {
          result.chat_ = chatBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf) {
          return mergeFrom((net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf other) {
        if (other == net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf.getDefaultInstance()) return this;
        if (other.hasChat()) {
          mergeChat(other.getChat());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.foreworld.gws.protobuf.Chat.ChatProtobuf chat_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.foreworld.gws.protobuf.Chat.ChatProtobuf, net.foreworld.gws.protobuf.Chat.ChatProtobuf.Builder, net.foreworld.gws.protobuf.Chat.ChatProtobufOrBuilder> chatBuilder_;
      /**
       * <code>optional .gws.ChatProtobuf chat = 1;</code>
       */
      public boolean hasChat() {
        return chatBuilder_ != null || chat_ != null;
      }
      /**
       * <code>optional .gws.ChatProtobuf chat = 1;</code>
       */
      public net.foreworld.gws.protobuf.Chat.ChatProtobuf getChat() {
        if (chatBuilder_ == null) {
          return chat_ == null ? net.foreworld.gws.protobuf.Chat.ChatProtobuf.getDefaultInstance() : chat_;
        } else {
          return chatBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .gws.ChatProtobuf chat = 1;</code>
       */
      public Builder setChat(net.foreworld.gws.protobuf.Chat.ChatProtobuf value) {
        if (chatBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          chat_ = value;
          onChanged();
        } else {
          chatBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .gws.ChatProtobuf chat = 1;</code>
       */
      public Builder setChat(
          net.foreworld.gws.protobuf.Chat.ChatProtobuf.Builder builderForValue) {
        if (chatBuilder_ == null) {
          chat_ = builderForValue.build();
          onChanged();
        } else {
          chatBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .gws.ChatProtobuf chat = 1;</code>
       */
      public Builder mergeChat(net.foreworld.gws.protobuf.Chat.ChatProtobuf value) {
        if (chatBuilder_ == null) {
          if (chat_ != null) {
            chat_ =
              net.foreworld.gws.protobuf.Chat.ChatProtobuf.newBuilder(chat_).mergeFrom(value).buildPartial();
          } else {
            chat_ = value;
          }
          onChanged();
        } else {
          chatBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .gws.ChatProtobuf chat = 1;</code>
       */
      public Builder clearChat() {
        if (chatBuilder_ == null) {
          chat_ = null;
          onChanged();
        } else {
          chat_ = null;
          chatBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .gws.ChatProtobuf chat = 1;</code>
       */
      public net.foreworld.gws.protobuf.Chat.ChatProtobuf.Builder getChatBuilder() {
        
        onChanged();
        return getChatFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .gws.ChatProtobuf chat = 1;</code>
       */
      public net.foreworld.gws.protobuf.Chat.ChatProtobufOrBuilder getChatOrBuilder() {
        if (chatBuilder_ != null) {
          return chatBuilder_.getMessageOrBuilder();
        } else {
          return chat_ == null ?
              net.foreworld.gws.protobuf.Chat.ChatProtobuf.getDefaultInstance() : chat_;
        }
      }
      /**
       * <code>optional .gws.ChatProtobuf chat = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.foreworld.gws.protobuf.Chat.ChatProtobuf, net.foreworld.gws.protobuf.Chat.ChatProtobuf.Builder, net.foreworld.gws.protobuf.Chat.ChatProtobufOrBuilder> 
          getChatFieldBuilder() {
        if (chatBuilder_ == null) {
          chatBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.foreworld.gws.protobuf.Chat.ChatProtobuf, net.foreworld.gws.protobuf.Chat.ChatProtobuf.Builder, net.foreworld.gws.protobuf.Chat.ChatProtobufOrBuilder>(
                  getChat(),
                  getParentForChildren(),
                  isClean());
          chat_ = null;
        }
        return chatBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gws.method.chat.send.ResponseProtobuf)
    }

    // @@protoc_insertion_point(class_scope:gws.method.chat.send.ResponseProtobuf)
    private static final net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf();
    }

    public static net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseProtobuf>
        PARSER = new com.google.protobuf.AbstractParser<ResponseProtobuf>() {
      public ResponseProtobuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseProtobuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseProtobuf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseProtobuf> getParserForType() {
      return PARSER;
    }

    public net.foreworld.gws.protobuf.method.chat.Send.ResponseProtobuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gws_method_chat_send_RequestProtobuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gws_method_chat_send_RequestProtobuf_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gws_method_chat_send_ResponseProtobuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gws_method_chat_send_ResponseProtobuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037protobuf/method.chat.send.proto\022\024gws.m" +
      "ethod.chat.send\032\031protobuf/model.chat.pro" +
      "to\"4\n\017RequestProtobuf\022\020\n\010receiver\030\001 \001(\t\022" +
      "\017\n\007comment\030\002 \001(\014\"3\n\020ResponseProtobuf\022\037\n\004" +
      "chat\030\001 \001(\0132\021.gws.ChatProtobufB.\n&net.for" +
      "eworld.gws.protobuf.method.chatB\004Sendb\006p" +
      "roto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.foreworld.gws.protobuf.Chat.getDescriptor(),
        }, assigner);
    internal_static_gws_method_chat_send_RequestProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gws_method_chat_send_RequestProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gws_method_chat_send_RequestProtobuf_descriptor,
        new java.lang.String[] { "Receiver", "Comment", });
    internal_static_gws_method_chat_send_ResponseProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gws_method_chat_send_ResponseProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gws_method_chat_send_ResponseProtobuf_descriptor,
        new java.lang.String[] { "Chat", });
    net.foreworld.gws.protobuf.Chat.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
