// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/method.user.get.proto

package net.foreworld.gws.protobuf.method.user;

public final class Get {
  private Get() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestProtobufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gws.method.user.get.RequestProtobuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();
  }
  /**
   * Protobuf type {@code gws.method.user.get.RequestProtobuf}
   */
  public  static final class RequestProtobuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gws.method.user.get.RequestProtobuf)
      RequestProtobufOrBuilder {
    // Use RequestProtobuf.newBuilder() to construct.
    private RequestProtobuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestProtobuf() {
      id_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestProtobuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.foreworld.gws.protobuf.method.user.Get.internal_static_gws_method_user_get_RequestProtobuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.foreworld.gws.protobuf.method.user.Get.internal_static_gws_method_user_get_RequestProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf.class, net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, id_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, id_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf)) {
        return super.equals(obj);
      }
      net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf other = (net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf) obj;

      boolean result = true;
      result = result && getId()
          .equals(other.getId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gws.method.user.get.RequestProtobuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gws.method.user.get.RequestProtobuf)
        net.foreworld.gws.protobuf.method.user.Get.RequestProtobufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.foreworld.gws.protobuf.method.user.Get.internal_static_gws_method_user_get_RequestProtobuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.foreworld.gws.protobuf.method.user.Get.internal_static_gws_method_user_get_RequestProtobuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf.class, net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf.Builder.class);
      }

      // Construct using net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.foreworld.gws.protobuf.method.user.Get.internal_static_gws_method_user_get_RequestProtobuf_descriptor;
      }

      public net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf getDefaultInstanceForType() {
        return net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf.getDefaultInstance();
      }

      public net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf build() {
        net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf buildPartial() {
        net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf result = new net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf(this);
        result.id_ = id_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf) {
          return mergeFrom((net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf other) {
        if (other == net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf.getDefaultInstance()) return this;
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gws.method.user.get.RequestProtobuf)
    }

    // @@protoc_insertion_point(class_scope:gws.method.user.get.RequestProtobuf)
    private static final net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf();
    }

    public static net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestProtobuf>
        PARSER = new com.google.protobuf.AbstractParser<RequestProtobuf>() {
      public RequestProtobuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestProtobuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestProtobuf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestProtobuf> getParserForType() {
      return PARSER;
    }

    public net.foreworld.gws.protobuf.method.user.Get.RequestProtobuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseProtobufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gws.method.user.get.ResponseProtobuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional .gws.UserProtobuf user = 1;</code>
     */
    boolean hasUser();
    /**
     * <code>optional .gws.UserProtobuf user = 1;</code>
     */
    net.foreworld.gws.protobuf.User.UserProtobuf getUser();
    /**
     * <code>optional .gws.UserProtobuf user = 1;</code>
     */
    net.foreworld.gws.protobuf.User.UserProtobufOrBuilder getUserOrBuilder();
  }
  /**
   * Protobuf type {@code gws.method.user.get.ResponseProtobuf}
   */
  public  static final class ResponseProtobuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gws.method.user.get.ResponseProtobuf)
      ResponseProtobufOrBuilder {
    // Use ResponseProtobuf.newBuilder() to construct.
    private ResponseProtobuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseProtobuf() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseProtobuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              net.foreworld.gws.protobuf.User.UserProtobuf.Builder subBuilder = null;
              if (user_ != null) {
                subBuilder = user_.toBuilder();
              }
              user_ = input.readMessage(net.foreworld.gws.protobuf.User.UserProtobuf.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(user_);
                user_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.foreworld.gws.protobuf.method.user.Get.internal_static_gws_method_user_get_ResponseProtobuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.foreworld.gws.protobuf.method.user.Get.internal_static_gws_method_user_get_ResponseProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf.class, net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    private net.foreworld.gws.protobuf.User.UserProtobuf user_;
    /**
     * <code>optional .gws.UserProtobuf user = 1;</code>
     */
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>optional .gws.UserProtobuf user = 1;</code>
     */
    public net.foreworld.gws.protobuf.User.UserProtobuf getUser() {
      return user_ == null ? net.foreworld.gws.protobuf.User.UserProtobuf.getDefaultInstance() : user_;
    }
    /**
     * <code>optional .gws.UserProtobuf user = 1;</code>
     */
    public net.foreworld.gws.protobuf.User.UserProtobufOrBuilder getUserOrBuilder() {
      return getUser();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (user_ != null) {
        output.writeMessage(1, getUser());
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (user_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getUser());
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf)) {
        return super.equals(obj);
      }
      net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf other = (net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf) obj;

      boolean result = true;
      result = result && (hasUser() == other.hasUser());
      if (hasUser()) {
        result = result && getUser()
            .equals(other.getUser());
      }
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasUser()) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUser().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gws.method.user.get.ResponseProtobuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gws.method.user.get.ResponseProtobuf)
        net.foreworld.gws.protobuf.method.user.Get.ResponseProtobufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.foreworld.gws.protobuf.method.user.Get.internal_static_gws_method_user_get_ResponseProtobuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.foreworld.gws.protobuf.method.user.Get.internal_static_gws_method_user_get_ResponseProtobuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf.class, net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf.Builder.class);
      }

      // Construct using net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (userBuilder_ == null) {
          user_ = null;
        } else {
          user_ = null;
          userBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.foreworld.gws.protobuf.method.user.Get.internal_static_gws_method_user_get_ResponseProtobuf_descriptor;
      }

      public net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf getDefaultInstanceForType() {
        return net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf.getDefaultInstance();
      }

      public net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf build() {
        net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf buildPartial() {
        net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf result = new net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf(this);
        if (userBuilder_ == null) {
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf) {
          return mergeFrom((net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf other) {
        if (other == net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf.getDefaultInstance()) return this;
        if (other.hasUser()) {
          mergeUser(other.getUser());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private net.foreworld.gws.protobuf.User.UserProtobuf user_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          net.foreworld.gws.protobuf.User.UserProtobuf, net.foreworld.gws.protobuf.User.UserProtobuf.Builder, net.foreworld.gws.protobuf.User.UserProtobufOrBuilder> userBuilder_;
      /**
       * <code>optional .gws.UserProtobuf user = 1;</code>
       */
      public boolean hasUser() {
        return userBuilder_ != null || user_ != null;
      }
      /**
       * <code>optional .gws.UserProtobuf user = 1;</code>
       */
      public net.foreworld.gws.protobuf.User.UserProtobuf getUser() {
        if (userBuilder_ == null) {
          return user_ == null ? net.foreworld.gws.protobuf.User.UserProtobuf.getDefaultInstance() : user_;
        } else {
          return userBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .gws.UserProtobuf user = 1;</code>
       */
      public Builder setUser(net.foreworld.gws.protobuf.User.UserProtobuf value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          user_ = value;
          onChanged();
        } else {
          userBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .gws.UserProtobuf user = 1;</code>
       */
      public Builder setUser(
          net.foreworld.gws.protobuf.User.UserProtobuf.Builder builderForValue) {
        if (userBuilder_ == null) {
          user_ = builderForValue.build();
          onChanged();
        } else {
          userBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .gws.UserProtobuf user = 1;</code>
       */
      public Builder mergeUser(net.foreworld.gws.protobuf.User.UserProtobuf value) {
        if (userBuilder_ == null) {
          if (user_ != null) {
            user_ =
              net.foreworld.gws.protobuf.User.UserProtobuf.newBuilder(user_).mergeFrom(value).buildPartial();
          } else {
            user_ = value;
          }
          onChanged();
        } else {
          userBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .gws.UserProtobuf user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = null;
          onChanged();
        } else {
          user_ = null;
          userBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .gws.UserProtobuf user = 1;</code>
       */
      public net.foreworld.gws.protobuf.User.UserProtobuf.Builder getUserBuilder() {
        
        onChanged();
        return getUserFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .gws.UserProtobuf user = 1;</code>
       */
      public net.foreworld.gws.protobuf.User.UserProtobufOrBuilder getUserOrBuilder() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilder();
        } else {
          return user_ == null ?
              net.foreworld.gws.protobuf.User.UserProtobuf.getDefaultInstance() : user_;
        }
      }
      /**
       * <code>optional .gws.UserProtobuf user = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          net.foreworld.gws.protobuf.User.UserProtobuf, net.foreworld.gws.protobuf.User.UserProtobuf.Builder, net.foreworld.gws.protobuf.User.UserProtobufOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              net.foreworld.gws.protobuf.User.UserProtobuf, net.foreworld.gws.protobuf.User.UserProtobuf.Builder, net.foreworld.gws.protobuf.User.UserProtobufOrBuilder>(
                  getUser(),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gws.method.user.get.ResponseProtobuf)
    }

    // @@protoc_insertion_point(class_scope:gws.method.user.get.ResponseProtobuf)
    private static final net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf();
    }

    public static net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseProtobuf>
        PARSER = new com.google.protobuf.AbstractParser<ResponseProtobuf>() {
      public ResponseProtobuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseProtobuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseProtobuf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseProtobuf> getParserForType() {
      return PARSER;
    }

    public net.foreworld.gws.protobuf.method.user.Get.ResponseProtobuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gws_method_user_get_RequestProtobuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gws_method_user_get_RequestProtobuf_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gws_method_user_get_ResponseProtobuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gws_method_user_get_ResponseProtobuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\036protobuf/method.user.get.proto\022\023gws.me" +
      "thod.user.get\032\031protobuf/model.user.proto" +
      "\"\035\n\017RequestProtobuf\022\n\n\002id\030\001 \001(\t\"3\n\020Respo" +
      "nseProtobuf\022\037\n\004user\030\001 \001(\0132\021.gws.UserProt" +
      "obufB-\n&net.foreworld.gws.protobuf.metho" +
      "d.userB\003Getb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          net.foreworld.gws.protobuf.User.getDescriptor(),
        }, assigner);
    internal_static_gws_method_user_get_RequestProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gws_method_user_get_RequestProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gws_method_user_get_RequestProtobuf_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_gws_method_user_get_ResponseProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gws_method_user_get_ResponseProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gws_method_user_get_ResponseProtobuf_descriptor,
        new java.lang.String[] { "User", });
    net.foreworld.gws.protobuf.User.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
