// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobuf/method.user.chat.proto

package net.foreworld.gws.protobuf.method.user;

public final class Chat {
  private Chat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RequestProtobufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gws.method.user.chat.RequestProtobuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string receiver = 1;</code>
     */
    java.lang.String getReceiver();
    /**
     * <code>optional string receiver = 1;</code>
     */
    com.google.protobuf.ByteString
        getReceiverBytes();

    /**
     * <code>optional bytes msg = 2;</code>
     */
    com.google.protobuf.ByteString getMsg();
  }
  /**
   * Protobuf type {@code gws.method.user.chat.RequestProtobuf}
   */
  public  static final class RequestProtobuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gws.method.user.chat.RequestProtobuf)
      RequestProtobufOrBuilder {
    // Use RequestProtobuf.newBuilder() to construct.
    private RequestProtobuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RequestProtobuf() {
      receiver_ = "";
      msg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private RequestProtobuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              receiver_ = s;
              break;
            }
            case 18: {

              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.foreworld.gws.protobuf.method.user.Chat.internal_static_gws_method_user_chat_RequestProtobuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.foreworld.gws.protobuf.method.user.Chat.internal_static_gws_method_user_chat_RequestProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf.class, net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf.Builder.class);
    }

    public static final int RECEIVER_FIELD_NUMBER = 1;
    private volatile java.lang.Object receiver_;
    /**
     * <code>optional string receiver = 1;</code>
     */
    public java.lang.String getReceiver() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        receiver_ = s;
        return s;
      }
    }
    /**
     * <code>optional string receiver = 1;</code>
     */
    public com.google.protobuf.ByteString
        getReceiverBytes() {
      java.lang.Object ref = receiver_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        receiver_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>optional bytes msg = 2;</code>
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getReceiverBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, receiver_);
      }
      if (!msg_.isEmpty()) {
        output.writeBytes(2, msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getReceiverBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, receiver_);
      }
      if (!msg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf)) {
        return super.equals(obj);
      }
      net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf other = (net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf) obj;

      boolean result = true;
      result = result && getReceiver()
          .equals(other.getReceiver());
      result = result && getMsg()
          .equals(other.getMsg());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + RECEIVER_FIELD_NUMBER;
      hash = (53 * hash) + getReceiver().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gws.method.user.chat.RequestProtobuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gws.method.user.chat.RequestProtobuf)
        net.foreworld.gws.protobuf.method.user.Chat.RequestProtobufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.foreworld.gws.protobuf.method.user.Chat.internal_static_gws_method_user_chat_RequestProtobuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.foreworld.gws.protobuf.method.user.Chat.internal_static_gws_method_user_chat_RequestProtobuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf.class, net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf.Builder.class);
      }

      // Construct using net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        receiver_ = "";

        msg_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.foreworld.gws.protobuf.method.user.Chat.internal_static_gws_method_user_chat_RequestProtobuf_descriptor;
      }

      public net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf getDefaultInstanceForType() {
        return net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf.getDefaultInstance();
      }

      public net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf build() {
        net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf buildPartial() {
        net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf result = new net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf(this);
        result.receiver_ = receiver_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf) {
          return mergeFrom((net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf other) {
        if (other == net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf.getDefaultInstance()) return this;
        if (!other.getReceiver().isEmpty()) {
          receiver_ = other.receiver_;
          onChanged();
        }
        if (other.getMsg() != com.google.protobuf.ByteString.EMPTY) {
          setMsg(other.getMsg());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object receiver_ = "";
      /**
       * <code>optional string receiver = 1;</code>
       */
      public java.lang.String getReceiver() {
        java.lang.Object ref = receiver_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          receiver_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public com.google.protobuf.ByteString
          getReceiverBytes() {
        java.lang.Object ref = receiver_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          receiver_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public Builder setReceiver(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        receiver_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public Builder clearReceiver() {
        
        receiver_ = getDefaultInstance().getReceiver();
        onChanged();
        return this;
      }
      /**
       * <code>optional string receiver = 1;</code>
       */
      public Builder setReceiverBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        receiver_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msg = 2;</code>
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>optional bytes msg = 2;</code>
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gws.method.user.chat.RequestProtobuf)
    }

    // @@protoc_insertion_point(class_scope:gws.method.user.chat.RequestProtobuf)
    private static final net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf();
    }

    public static net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RequestProtobuf>
        PARSER = new com.google.protobuf.AbstractParser<RequestProtobuf>() {
      public RequestProtobuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new RequestProtobuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RequestProtobuf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RequestProtobuf> getParserForType() {
      return PARSER;
    }

    public net.foreworld.gws.protobuf.method.user.Chat.RequestProtobuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseProtobufOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gws.method.user.chat.ResponseProtobuf)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional bytes sender = 1;</code>
     */
    com.google.protobuf.ByteString getSender();

    /**
     * <code>optional bytes msg = 2;</code>
     */
    com.google.protobuf.ByteString getMsg();
  }
  /**
   * Protobuf type {@code gws.method.user.chat.ResponseProtobuf}
   */
  public  static final class ResponseProtobuf extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:gws.method.user.chat.ResponseProtobuf)
      ResponseProtobufOrBuilder {
    // Use ResponseProtobuf.newBuilder() to construct.
    private ResponseProtobuf(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ResponseProtobuf() {
      sender_ = com.google.protobuf.ByteString.EMPTY;
      msg_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ResponseProtobuf(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              sender_ = input.readBytes();
              break;
            }
            case 18: {

              msg_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return net.foreworld.gws.protobuf.method.user.Chat.internal_static_gws_method_user_chat_ResponseProtobuf_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return net.foreworld.gws.protobuf.method.user.Chat.internal_static_gws_method_user_chat_ResponseProtobuf_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf.class, net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf.Builder.class);
    }

    public static final int SENDER_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString sender_;
    /**
     * <code>optional bytes sender = 1;</code>
     */
    public com.google.protobuf.ByteString getSender() {
      return sender_;
    }

    public static final int MSG_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString msg_;
    /**
     * <code>optional bytes msg = 2;</code>
     */
    public com.google.protobuf.ByteString getMsg() {
      return msg_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!sender_.isEmpty()) {
        output.writeBytes(1, sender_);
      }
      if (!msg_.isEmpty()) {
        output.writeBytes(2, msg_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!sender_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, sender_);
      }
      if (!msg_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, msg_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf)) {
        return super.equals(obj);
      }
      net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf other = (net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf) obj;

      boolean result = true;
      result = result && getSender()
          .equals(other.getSender());
      result = result && getMsg()
          .equals(other.getMsg());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SENDER_FIELD_NUMBER;
      hash = (53 * hash) + getSender().hashCode();
      hash = (37 * hash) + MSG_FIELD_NUMBER;
      hash = (53 * hash) + getMsg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gws.method.user.chat.ResponseProtobuf}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:gws.method.user.chat.ResponseProtobuf)
        net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobufOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return net.foreworld.gws.protobuf.method.user.Chat.internal_static_gws_method_user_chat_ResponseProtobuf_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return net.foreworld.gws.protobuf.method.user.Chat.internal_static_gws_method_user_chat_ResponseProtobuf_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf.class, net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf.Builder.class);
      }

      // Construct using net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        sender_ = com.google.protobuf.ByteString.EMPTY;

        msg_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return net.foreworld.gws.protobuf.method.user.Chat.internal_static_gws_method_user_chat_ResponseProtobuf_descriptor;
      }

      public net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf getDefaultInstanceForType() {
        return net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf.getDefaultInstance();
      }

      public net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf build() {
        net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf buildPartial() {
        net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf result = new net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf(this);
        result.sender_ = sender_;
        result.msg_ = msg_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf) {
          return mergeFrom((net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf other) {
        if (other == net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf.getDefaultInstance()) return this;
        if (other.getSender() != com.google.protobuf.ByteString.EMPTY) {
          setSender(other.getSender());
        }
        if (other.getMsg() != com.google.protobuf.ByteString.EMPTY) {
          setMsg(other.getMsg());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString sender_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes sender = 1;</code>
       */
      public com.google.protobuf.ByteString getSender() {
        return sender_;
      }
      /**
       * <code>optional bytes sender = 1;</code>
       */
      public Builder setSender(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sender_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes sender = 1;</code>
       */
      public Builder clearSender() {
        
        sender_ = getDefaultInstance().getSender();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString msg_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes msg = 2;</code>
       */
      public com.google.protobuf.ByteString getMsg() {
        return msg_;
      }
      /**
       * <code>optional bytes msg = 2;</code>
       */
      public Builder setMsg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        msg_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes msg = 2;</code>
       */
      public Builder clearMsg() {
        
        msg_ = getDefaultInstance().getMsg();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:gws.method.user.chat.ResponseProtobuf)
    }

    // @@protoc_insertion_point(class_scope:gws.method.user.chat.ResponseProtobuf)
    private static final net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf();
    }

    public static net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ResponseProtobuf>
        PARSER = new com.google.protobuf.AbstractParser<ResponseProtobuf>() {
      public ResponseProtobuf parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ResponseProtobuf(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ResponseProtobuf> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResponseProtobuf> getParserForType() {
      return PARSER;
    }

    public net.foreworld.gws.protobuf.method.user.Chat.ResponseProtobuf getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gws_method_user_chat_RequestProtobuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gws_method_user_chat_RequestProtobuf_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_gws_method_user_chat_ResponseProtobuf_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_gws_method_user_chat_ResponseProtobuf_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\037protobuf/method.user.chat.proto\022\024gws.m" +
      "ethod.user.chat\"0\n\017RequestProtobuf\022\020\n\010re" +
      "ceiver\030\001 \001(\t\022\013\n\003msg\030\002 \001(\014\"/\n\020ResponsePro" +
      "tobuf\022\016\n\006sender\030\001 \001(\014\022\013\n\003msg\030\002 \001(\014B.\n&ne" +
      "t.foreworld.gws.protobuf.method.userB\004Ch" +
      "atb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_gws_method_user_chat_RequestProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_gws_method_user_chat_RequestProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gws_method_user_chat_RequestProtobuf_descriptor,
        new java.lang.String[] { "Receiver", "Msg", });
    internal_static_gws_method_user_chat_ResponseProtobuf_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_gws_method_user_chat_ResponseProtobuf_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_gws_method_user_chat_ResponseProtobuf_descriptor,
        new java.lang.String[] { "Sender", "Msg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
